Repository Bixal/bixal-site-drupal, pull requests merged in 2024-02, with the labels that each got.

#85 Fixes #77: Description list missing vertical line when logged in
  stories/assets/styles/global/global.scss
  stories/components/description-list/description-list-base.html.twig
  stories/components/description-list/description-list-collection-base.html.twig
  stories/components/description-list/description-list-collection.html.twig
  stories/components/description-list/description-list.html.twig
  stories/partials/media-image.html.twig
  vite.config.js
  web/themes/custom/bixal_uswds/bixal_uswds.info.yml
  web/themes/custom/bixal_uswds/templates/media/media--image--description-list.html.twig
  web/themes/custom/bixal_uswds/templates/media/media--image.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--description-list-collection.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--description-list.html.twig
Labels: Drupal, Storybook

#83 BSD-53: Case studies
  config/sync/core.entity_view_display.node.blog.teaser.yml
  stories/components/blurb/blurb-base.html.twig
  stories/components/blurb/blurb-collection-base.html.twig
  stories/components/blurb/blurb-collection-featured.content.json
  stories/components/blurb/blurb-collection.content.json
  stories/components/blurb/blurb-collection.html.twig
  stories/components/blurb/blurb.html.twig
  stories/components/blurb/blurb.scss
  stories/components/blurb/blurb.stories.js
  stories/components/button/button.html.twig
  stories/components/description-list/description-list.html.twig
  stories/components/section/section.html.twig
  stories/pages/careers/careers.stories.js
  stories/pages/case-studies-landing/case-studies-landing.html.twig
  stories/pages/case-studies-landing/case-studies-landing.stories.js
  stories/pages/case-study/case-study.html.twig
  stories/pages/case-study/case-study.stories.js
  web/themes/custom/bixal_uswds/templates/node/node--blog--teaser.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--blurb-collection.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--blurb.html.twig
  web/themes/custom/bixal_uswds/templates/views/views-view--blog.html.twig
Labels: Storybook

#80 Feature/bsd 75 people node page
  config/sync/core.entity_form_display.paragraph.button.default.yml
  config/sync/core.entity_view_display.node.bixaler.default.yml
  config/sync/core.entity_view_display.paragraph.button.default.yml
  config/sync/field.field.paragraph.button.field_button_variant.yml
  config/sync/field.field.paragraph.button.field_has_icon.yml
  config/sync/field.field.paragraph.button.field_icon.yml
  config/sync/field.field.paragraph.button.field_modifier.yml
  config/sync/field.storage.paragraph.field_button_variant.yml
  config/sync/field.storage.paragraph.field_has_icon.yml
  config/sync/field.storage.paragraph.field_icon.yml
  config/sync/field.storage.paragraph.field_modifier.yml
  config/sync/system.site.yml
  config/sync/views.view.bixalers.yml
  stories/components/profile/profile-base.html.twig
  stories/components/profile/profile.content.json
  stories/components/profile/profile.html.twig
  stories/components/profile/profile.scss
  stories/components/section/section.html.twig
  stories/components/section/section.stories.js
  stories/pages/about-landing/_people-section.html.twig
  stories/pages/careers/_benefits.html.twig
  stories/pages/careers/_featured-jobs.html.twig
  stories/pages/careers/_how-we-work.html.twig
  stories/pages/case-studies-landing/case-studies-landing.html.twig
  stories/pages/case-study/case-study.html.twig
  stories/pages/homepage/_clients-and-partners.html.twig
  stories/pages/homepage/_core-services.html.twig
  web/modules/custom/bixal_default_content/content/node/24fbd4e2-27b4-4cb1-b3c6-264a33426868.yml
  web/modules/custom/bixal_default_content/content/node/71dd8e30-66cf-4dd1-9bee-6e26e6ed57d5.yml
  web/modules/custom/bixal_default_content/content/node/cc32d22a-2886-4359-a7ae-87d50d114cd5.yml
  web/modules/custom/bixal_default_content/content/node/ed430371-da05-4a2b-a686-80fe68d22d7c.yml
  web/themes/custom/bixal_uswds/src/js/header.js
  web/themes/custom/bixal_uswds/src/js/people-list.js
  web/themes/custom/bixal_uswds/src/js/toggle.js
  web/themes/custom/bixal_uswds/templates/node/node--bixaler--full.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--section-wrapper.html.twig
  web/themes/custom/bixal_uswds/templates/paragraphs/paragraph--section.html.twig
Labels: Drupal
